version: '2'
services:
    script:
        container_name: gw_script_container
        build: .
        volumes:
            - ${VOL}:/app
        environment:
          CONDA_DEFAULT_ENV: base
          _: /opt/conda/bin/python
          CONDA_EXE: /opt/conda/bin/conda
          SHLVL: 1
          CONDA_PYTHON_EXE: /opt/conda/bin/python
          CONDA_SHLVL: 1
          CONDA_PROMPT_MODIFIER: (base)
          PROJ_LIB: /opt/conda/share/proj
          CONDA_PREFIX: /opt/conda

