version: '2'
services:
    script:
        container_name: gw_base_container
        build: .
        volumes:
            - ${VOL}:/app
        links:
            - db
        environment:
          CONDA_DEFAULT_ENV: base
          _: /opt/conda/bin/python
          CONDA_EXE: /opt/conda/bin/conda
          SHLVL: 1
          CONDA_PYTHON_EXE: /opt/conda/bin/python
          CONDA_SHLVL: 1
          CONDA_PROMPT_MODIFIER: (base)
          PROJ_LIB: /opt/conda/share/proj
          CONDA_PREFIX: /opt/conda
    db:
      container_name: gw_base_db
      image: "mysql:8.0.16"
      command: mysqld --default-authentication-plugin=mysql_native_password
      ports:
        - "53307:3306"
      volumes:
        - ${VOL_DB}:/var/lib/mysql
        - ${VOL_DB_CONFIG}:/etc/mysql/conf.d
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_PWD}

